language: node_js

node_js: 8

services:
  - mongodb

env:
  - CXX=g++-4.8

branches:
  only:
    - master
    - staging

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  hosts:
    - localhost

before_script:
  - npm install -g grunt-cli
  - sleep 10

script:
  - grunt coverage
