language: node_js

node_js: 8

jobs:
  include:

  - stage: install, check code style and coverage
    services:
    - mongodb
    env:
    - CXX=g++-4.8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
      hosts:
      - localhost
    before_script:
    - npm install -g grunt-cli
    - sleep 10
    script:
    - grunt
    - if [ "$TRAVIS_BRANCH" != "master" ]; then grunt test; fi
    - if [ "$TRAVIS_BRANCH" = "master" ]; then grunt coverage; fi
